
const routeLinks = {
  auth: {
    path:'/auth/',
    login: '/auth/login',
    register: '/auth/register',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    emailVerification: '/auth/email-verification',
    updatePassword: '/auth/update-password',
    partnerAuth: '/auth/practitioners',
    partnerLogin: '/auth/practitioners/login',
    partnerEmailVerification: '/auth/practitioners/email-verification',
    adminAuth: '/auth/admin',
    adminLogin: '/auth/admin/login',
  },
  patient: {
    path:'/patient',
    lab:'/patient/lab',
    labDetails:'/patient/lab/:id',
    orders:'/patient/orders',
    orderDetails:'/patient/orders/:id',
    profile: '/patient/profile',
    pharmacy:'/patient/pharmacy',
    dashboard: '/patient/dashboard',
    onboarding:'/patient/onboarding',
    appointment:'/patient/appointment-booking',
    consultations: '/patient/consultations',
     consultationsid: '/patient/consultations/:id',
    prescription:'/patient/prescription',
    medicalHistory:'/patient/diagnosis',
    checkout:'/patient/checkout',
    helpCenter:'/patient/helpcenter',
    vitals: '/patient/vitals',
    vitalsDetails: '/patient/vitals/:id',
    procedures : '/patient/procedures',
    proceduresDetails : '/patient/procedures/:id',
    notification: '/patient/notifications',

  },
  doctor: {
    path:'/doctor',
    patients:'/doctor/patients',
    allPatients:'/doctor/all-patients',
    allPatientsDetails:'/doctor/all-patients/:id',
    profile:'/doctor/profile-management',
    dashboard:'/doctor/dashboard',
    schedule:'/doctor/schedule',
    appointment:'/doctor/appointments',
    prescription:'/doctor/prescriptions',
    labOrders:'/doctor/lab-orders',
    labOrdersDetails:'/doctor/lab-orders/:id',
    appointmentView : '/doctor/appointments/:id',
    patientView : '/doctor/patients/:id',
      helpCenter:'/doctor/helpcenter',
      procedures:'/doctor/procedures',
      proceduresDetails:'/doctor/procedures/:id',
      notification: '/doctor/notifications',
},
nurse : {
  path: '/nurse',
  dashboard: '/nurse/dashboard',
  profile: '/nurse/profile',
  helpCenter:'/nurse/helpcenter',
  reports: '/nurse/reports',
  reportsDetails: '/nurse/reports/:id',
  reportsAdd: '/nurse/reports/create',
  reportsEdit : '/nurse/reports/edit/:id',
  vitals: '/nurse/vitals',
  vitalsDetails: '/nurse/vitals/:id',
  procedures : '/nurse/procedures',
  proceduresDetails : '/nurse/procedures/:id',
  patient : '/nurse/patients',
  patientDetails : '/nurse/patients/:id',
  notification: '/nurse/notifications',
},
matron : {
  path: '/matron',
  dashboard: '/matron/dashboard',
  profile: '/matron/profile',
  helpCenter:'/matron/helpcenter',
  reports: '/matron/reports',
  reportsDetails: '/matron/reports/:id',
  vitals: '/matron/vitals',
  reportsAdd: '/matron/reports/create',
   reportsEdit : '/matron/reports/edit/:id',
  vitalsDetails: '/matron/vitals/:id',
   procedures : '/matron/procedures',
  proceduresDetails : '/matron/procedures/:id',
  patient : '/matron/patients',
  patientDetails : '/matron/patients/:id',
  notification: '/matron/notifications',
},
lab: { 
    path:'/lab',
    dashboard: '/lab/dashboard',
    labRequests: '/lab/requests',  
    labRequestsDetails: '/lab/requests/:id', 
    profile: '/lab/profile',
    helpCenter:'/lab/helpcenter',
    notification: '/lab/notifications',
},

admin: {
  path:'/admin',
  dashboard: '/admin/dashboard',
    users: '/admin/users',
    usersDetails: '/admin/users/:id',
  patients: '/admin/patients',
  patientsStats: '/admin/patients-stats',
  patientsDetails: '/admin/patients/:id',
  orders: '/admin/orders',
  orderDetails: '/admin/orders/:id',
  appointments: '/admin/appointments',
  appointmentDetails: '/admin/appointments/:id',
  profile: '/admin/profile',
  settings: '/admin/settings',
  notifications: '/admin/notifications',
  reports: '/admin/reports',
  lab: '/admin/lab',
  labDetails: '/admin/lab/:id',
  pharmacists: '/admin/pharmacists',
  pharmacistsDetails: '/admin/pharmacists/:id',
  consultations: '/admin/consultations',
  consultationsDetails: '/admin/consultations/:id',
  doctors: '/admin/doctors',
    doctorsStats:'/admin/doctors-stats',
  doctorsSpecialties:'/admin/doctors-specialties',
  doctorDetails: '/admin/doctors/:id',
  medications:'/admin/medications',
  medicationsDetails:'/admin/medications/:id',
  admin:'/admin/admins',
  adminsDetails: '/admin/admins/:id',
  adminInventory: '/admin/inventory',
  adminInventoryDetails:'/admin/inventory/:id',
  adminInventoryCreate:'/admin/inventory/create/:id',
  adminInventoryLogs: '/admin/inventory-logs',
  adminInventorySummary: '/admin/inventory-summary',
   adminInventoryMedication: '/admin/inventory/medication/:id',
   helpCenter:'/admin/helpcenter',
  nurses : '/admin/nurses',
  nurseDetails : '/admin/nurses/:id',
  vitals : '/admin/vitals',
  vitalDetails : '/admin/vitals/:id',
  procedures: '/admin/procedures',
  proceduresDetails: '/admin/procedures/:id',
  partners: '/admin/partners',
  partnersDetails: '/admin/partners/:id',
  services: '/admin/services',
  servicesDetails: '/admin/services/:id',
  notification: '/admin/notifications',
},
superAdmin: {
  path:'/super-admin',
  dashboard: '/super-admin/dashboard',
  orders: '/super-admin/orders',
  orderDetails: '/super-admin/orders/:id',
     users: '/super-admin/users',
    usersDetails: '/super-admin/users/:id',
  patients: '/super-admin/patients',
  patientsStats: '/super-admin/patients-stats',
  patientsDetails: '/super-admin/patients/:id',
  appointments: '/super-admin/appointments',
  appointmentDetails: '/super-admin/appointments/:id',
  profile: '/super-admin/profile',
  settings: '/super-admin/settings',
  notifications: '/super-admin/notifications',
  reports: '/super-admin/reports',
  lab: '/super-admin/lab',
  labDetails: '/super-admin/lab/:id',
  pharmacists: '/super-admin/pharmacists',
  pharmacistsDetails: '/super-admin/pharmacists/:id',
  consultations: '/super-admin/consultations',
  consultationsDetails: '/super-admin/consultations/:id',
  doctors: '/super-admin/doctors',
  doctorsStats:'/super-admin/doctors-stats',
  doctorsSpecialties:'/super-admin/doctors-specialties',
  doctorDetails: '/super-admin/doctors/:id',
  medications:'/super-admin/medications',
  medicationsDetails:'/super-admin/medications/:id',
  admins: '/super-admin/admins',
  adminsDetails: '/super-admin/admins/:id',
  adminInventory: '/super-admin/inventory',
  adminInventoryDetails:'/super-admin/inventory/:id',
  adminInventoryLogs: '/super-admin/inventory-logs',
  adminInventorySummary: '/super-admin/inventory-summary',
  adminInventoryMedication: '/super-admin/inventory/medication/:id',
  helpCenter:'/super-admin/helpcenter',
  nurses: '/super-admin/nurses',
  nurseDetails : '/super-admin/nurses/:id',
  vitals : '/super-admin/vitals',
  vitalDetails : '/super-admin/vitals/:id',
  procedures: '/super-admin/procedures',
  proceduresDetails: '/super-admin/procedures/:id',
  partners: '/super-admin/partners',
  partnersDetails: '/super-admin/partners/:id',
  services: '/super-admin/services',
  servicesDetails: '/super-admin/services/:id',
  notification: '/super-admin/notifications',
},
pharmacist: {
  path:'/pharmacist',
  dashboard: '/pharmacist/dashboard',
  medications:'/pharmacist/medications',
  orders:'/pharmacist/orders',
  orderDetails:'/pharmacist/orders/:id',
  pharmacistInventory: '/pharmacist/inventory',
  pharmacistInventoryDetails:'/pharmacist/inventory/:id',
  pharmacistInventorySummary: '/pharmacist/inventory-summary',
  pharmacistInventoryMedication: '/pharmacist/inventory/medication/:id',
  profile:'/pharmacist/profile',
  helpCenter:'/pharmacist/helpcenter',
  notification: '/pharmacist/notifications',
}
}

export default routeLinks