
const routeLinks = {
  auth: {
    path:'/auth',
    login: '/auth/login',
    register: '/auth/register',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    emailVerification: '/auth/email-verification',
    updatePassword: '/auth/update-password',
    partnerAuth: '/auth/practitioners',
    partnerLogin: '/auth/practitioners/login',
    partnerEmailVerification: '/auth/practitioners/email-verification',
    adminAuth: '/auth/admin',
    adminLogin: '/auth/admin/login',
  },
  patient: {
    path:'/patient',
    lab:'/patient/lab',
    labDetails:'/patient/lab/:id',
    orders:'/patient/orders',
    orderDetails:'/patient/orders/:id',
    profile: '/patient/profile',
    pharmacy:'/patient/pharmacy',
    dashboard: '/patient/dashboard',
    onboarding:'/patient/onboarding',
    appointment:'/patient/appointment-booking',
    consultations: '/patient/consultations',
     consultationsid: '/patient/consultations/:id',
    prescription:'/patient/prescription',
    medicalHistory:'/patient/diagnosis'

  },
  doctor: {
    path:'/doctor',
    patients:'/doctor/patients',
    profile:'/doctor/profile-management',
    dashboard:'/doctor/dashboard',
    schedule:'/doctor/schedule',
    appointment:'/doctor/appointments',
    prescription:'/doctor/prescriptions',
    labOrders:'/doctor/lab-orders',
    labOrdersDetails:'/doctor/lab-orders/:id',
    appointmentView : '/doctor/appointments/:id',
    patientView : '/doctor/patients/:id',
},

lab: { 
    path:'/lab',
    dashboard: '/lab/dashboard',
    labRequests: '/lab/requests',  
    labRequestsDetails: '/lab/requests/:id', 
    profile: '/lab/profile',
},

admin: {
  path:'/admin',
  dashboard: '/admin/dashboard',
  patients: '/admin/patients',
  patientsDetails: '/admin/patients/:id',
  appointments: '/admin/appointments',
  appointmentDetails: '/admin/appointments/:id',
  profile: '/admin/profile',
  settings: '/admin/settings',
  notifications: '/admin/notifications',
  reports: '/admin/reports',
  lab: '/admin/lab',
  labDetails: '/admin/lab/:id',
  pharmacists: '/admin/pharmacists',
  pharmacistsDetails: '/admin/pharmacists/:id',
  consultations: '/admin/consultations',
  consultationsDetails: '/admin/consultations/:id',
  doctors: '/admin/doctors',
  doctorDetails: '/admin/doctors/:id',
  medications:'/admin/medications',
  medicationsDetails:'/super-admin/medications/:id',
  admin:'/admin/admins',
  adminsDetails: '/admin/admins/:id',
  adminInventory: '/admin/inventory',
  adminInventoryDetails:'/admin/inventory/:id',
  adminInventoryCreate:'/admin/inventory/create/:id',
  adminInventoryLogs: '/admin/inventory-logs',
  adminInventorySummary: '/admin/inventory-summary',
   adminInventoryMedication: '/admin/inventory/medication/:id',
},
superAdmin: {
  path:'/super-admin',
  dashboard: '/super-admin/dashboard',
  patients: '/super-admin/patients',
  patientsDetails: '/super-admin/patients/:id',
  appointments: '/super-admin/appointments',
  appointmentDetails: '/super-admin/appointments/:id',
  profile: '/super-admin/profile',
  settings: '/super-admin/settings',
  notifications: '/super-admin/notifications',
  reports: '/super-admin/reports',
  lab: '/super-admin/lab',
  labDetails: '/super-admin/lab/:id',
  pharmacists: '/super-admin/pharmacists',
  pharmacistsDetails: '/super-admin/pharmacists/:id',
  consultations: '/super-admin/consultations',
  consultationsDetails: '/super-admin/consultations/:id',
  doctors: '/super-admin/doctors',
  doctorDetails: '/super-admin/doctors/:id',
  medications:'/super-admin/medications',
  medicationsDetails:'/super-admin/medications/:id',
  admins: '/super-admin/admins',
  adminsDetails: '/super-admin/admins/:id',
  adminInventory: '/super-admin/inventory',
  adminInventoryDetails:'/super-admin/inventory/:id',
  adminInventoryLogs: '/super-admin/inventory-logs',
  adminInventorySummary: '/super-admin/inventory-summary',
  adminInventoryMedication: '/super-admin/inventory/medication/:id',
},
pharmacist: {
  path:'/pharmacist',
  dashboard: '/pharmacist/dashboard',
  medications:'/pharmacist/medications',
  pharmacistInventory: '/pharmacist/inventory',
  pharmacistInventoryDetails:'/pharmacist/inventory/:id',
  pharmacistInventorySummary: '/pharmacist/inventory-summary',
  pharmacistInventoryMedication: '/pharmacist/inventory/medication/:id',
  profile:'/pharmacist/profile'
}
}

export default routeLinks